// src/components/Header.tsx
import { ConnectKitButton } from "connectkit";

export function Header() {
  return (
    <header className="flex justify-between items-center mb-8 border-b border-gray-100 pb-4">
      <h1 className="text-2xl font-bold text-gray-800 tracking-tight">Olla Dashboard</h1>
      <ConnectKitButton />
    </header>
  );
}

// lsp-svelte-minimal/src/lib/components/Header.svelte
<script lang="ts">
	// Reown AppKit web component handles the button state automatically
</script>

<header class="flex justify-between items-center mb-8 border-b border-gray-100 pb-4">
    <h1 class="text-2xl font-bold text-gray-800 tracking-tight">Olla Dashboard</h1>
    
    <!-- This web component is provided by @reown/appkit -->
    <appkit-button />
</header>
